# Generated by Django 5.2.4 on 2025-08-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
