# Generated by Django 5.2.4 on 2025-08-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_username', models.CharField(max_length=200)),
                ('entered_password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phishing_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.phishinglink')),
            ],
        ),
    ]
